### ISSUE TITLE
process killed in dbp_yg dataset

### ISSUE THREAD

**Issue by JadeXIN** [StephanieWyt/NMN#1]
Hi,

My process will be killed by itself when I run dataset dbp_yg. But there is no problem with the other datasets. Is there any parameters or other issues I ignored?

Best Regards.
![1595229202](https://user-images.githubusercontent.com/20750125/87909968-8f903600-caac-11ea-97ca-712f69f6a686.png)

**Comment by StephanieWyt** [comment]
Hi,
Thanks for your interest in our work! I guess the reason for the process being killed by the system might be insufficient memory, since the dbp_yg dataset is much larger than dbp15k. You can try using a smaller batch size to reduce memory usage.

Best
Yuting

**Comment by JadeXIN** [comment]
Thank you.
